apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: vpn
  labels:
    name: prometheus
spec:
  type: ClusterIP
  ports:
    - name: prometheus-tcp
      targetPort: 9090
      protocol: TCP
      port: 9090
  selector:
    name: prometheus
