plugin: community.general.yc_compute
auth_kind: "serviceaccountfile"
service_account_file: "stubs/sa.json"
folders:
  - FOLDER_ID
hostnames:
  - public_ip
keyed_groups:
  - key: labels.tags
    prefix: ''
    separator: ''
