version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME_AROUND_DOMAIN}/ui:${UI_VERSION}
    volumes:
      - ./ui:/app
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
    command: ["puma", "--debug", "-w", "2"]
  post:
    image: ${USERNAME_AROUND_DOMAIN}/post:${POST_VERSION}
    volumes:
      - ./post-py:/app
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME_AROUND_DOMAIN}/comment:${COMMENT_VERSION}
    volumes:
      - ./comment:/app
    networks:
      - back_net
      - front_net
    command: ["puma", "--debug", "-w", "2"]

volumes:
  post_db:

networks:
  back_net:
  front_net:
